#!/bin/bash
set -e

name=${1%.*}
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Running CVC4..."
cvc4 --proof --dump-proof --no-simplification --fewer-preprocessing-holes --no-bv-eq --no-bv-ineq --no-bv-algebraic $1 > $name.lfsc

sed -i -e '1d' $name.lfsc

echo "Creating Coq file..."
cat > ${name}_lfsc.v <<EOF
Require Import SMTCoq Bool List.
Import ListNotations BVList.BITVECTOR_LIST FArray.
Local Open Scope list_scope.
Local Open Scope farray_scope.
Local Open Scope bv_scope.

Section File.
  Lfsc_Checker "$name.smt2" "$name.lfsc".
End File.
EOF

# echo "Checking LFSC proof with Coq directly..."
coqc -q -R $DIR/../.. SMTCoq ${name}_lfsc.v

exit 0

