#!/usr/bin/env bash

set -e

shift 1
DEPS=$*

MODULES=""
MODULES+=$'\n'"  abduce_tactics"
MODULES+=$'\n'"  lfsc_tactics"
MODULES+=$'\n'"  verit_tactics"
MODULES+=$'\n'"  zchaff_tactics"

function lfsc() {
    FILENAME=$1

    # TODO
    [[ "${FILENAME}" == hole4 ]] && return
    [[ "${FILENAME}" =~ lia[0-9]* ]] && return
    [[ "${FILENAME}" == sat5 ]] && return
    [[ "${FILENAME}" == sat7 ]] && return
    [[ "${FILENAME}" == sat9 ]] && return
    [[ "${FILENAME}" == sat10 ]] && return
    [[ "${FILENAME}" == sat11 ]] && return
    [[ "${FILENAME}" == sat12 ]] && return
    [[ "${FILENAME}" == sat13 ]] && return
    [[ "${FILENAME}" == sat14 ]] && return
    [[ "${FILENAME}" == uf1 ]] && return
    [[ "${FILENAME}" == uf3 ]] && return
    [[ "${FILENAME}" == uf4 ]] && return
    [[ "${FILENAME}" == uf5 ]] && return

    cat <<EOF
(rule
 (target ${FILENAME}.lfsc)
 (deps ${FILENAME}.smt2)
 (action
  (with-stdout-to
   %{target}
   (run
    cvc4
    --proof
    --dump-proof
    --fewer-preprocessing-holes
    --no-bv-eq
    --no-bv-ineq
    --no-bv-algebraic
    --allow-empty-dependencies
    %{deps}))))

EOF

    cat <<EOF
(rule
 (target lfsc_vernac_${FILENAME}.v)
 (deps ${FILENAME}.smt2 ${FILENAME}.lfsc)
 (action
  (write-file
   %{target}
   "From SMTCoq Require Import SMTCoq.\nSection Checker.\n  Lfsc_Checker \"unit-tests/${FILENAME}.smt2\" \"unit-tests/${FILENAME}.lfsc\".\nEnd Checker.\n")))

EOF

    MODULES+=$'\n'"  lfsc_vernac_${FILENAME}"
}


function verit() {
    FILENAME=$1

    [[ "${FILENAME}" =~ bv[0-9]* ]] && return

    # TODO
    [[ "${FILENAME}" == ex1 ]] && return
    [[ "${FILENAME}" == sat10 ]] && return

    cat <<EOF
(rule
 (target ${FILENAME}.vtlog)
 (deps ${FILENAME}.smt2)
 (action
  (ignore-stdout
   (run
    veriT
    --proof-prune
    --proof-merge
    --proof-with-sharing
    --cnf-definitional
    --disable-ackermann
    --input=smtlib2
    --proof=%{target}
    %{deps}))))

EOF

    cat <<EOF
(rule
 (target verit_vernac_${FILENAME}.v)
 (deps ${FILENAME}.smt2 ${FILENAME}.vtlog)
 (action
  (write-file
   %{target}
   "From SMTCoq Require Import SMTCoq.\nSection File.\n  Verit_Checker \"unit-tests/${FILENAME}.smt2\" \"unit-tests/${FILENAME}.vtlog\".\nEnd File.\nSection Thm.\n  Verit_Theorem thm \"unit-tests/${FILENAME}.smt2\" \"unit-tests/${FILENAME}.vtlog\".\nEnd Thm.\nSection Parse.\n  Parse_certif_verit t_i t_func t_atom t_form root used_roots trace \"unit-tests/${FILENAME}.smt2\" \"unit-tests/${FILENAME}.vtlog\".\n  Compute @Euf_Checker.checker t_i t_func t_atom t_form root used_roots trace.\nEnd Parse.\n")))

EOF

    MODULES+=$'\n'"  verit_vernac_${FILENAME}"
}


function zchaff() {
    FILENAME=$1

    cat <<EOF
(rule
 (target ${FILENAME}.zlog)
 (deps run_zchaff.sh ${FILENAME}.cnf)
 (action
  (ignore-stdout
   (run ./run_zchaff.sh %{deps} %{target}))))

EOF

    cat <<EOF
(rule
 (target zchaff_vernac_${FILENAME}.v)
 (deps ${FILENAME}.cnf ${FILENAME}.zlog)
 (action
  (write-file
   %{target}
   "From SMTCoq Require Import SMTCoq.\nSection Checker.\n  Zchaff_Checker \"unit-tests/${FILENAME}.cnf\" \"unit-tests/${FILENAME}.zlog\".\nEnd Checker.\nSection Thm.\n  Zchaff_Theorem thm \"unit-tests/${FILENAME}.cnf\" \"unit-tests/${FILENAME}.zlog\".\nEnd Thm.\nSection Parse.\n  Parse_certif_zchaff d t \"unit-tests/${FILENAME}.cnf\" \"unit-tests/${FILENAME}.zlog\".\n  Compute Sat_Checker.checker d t.\nEnd Parse.\n")))

EOF

    MODULES+=$'\n'"  zchaff_vernac_${FILENAME}"
}


cat <<EOF
; This file has been generated by dune. Do not edit.
; Once this file is modified, track it with git.

EOF

for FILE in ${DEPS}
do

    case "${FILE}" in
        *.cnf)
            FILENAME="${FILE%.cnf}"
            zchaff "${FILENAME}"
            ;;
        *.smt2)
            FILENAME="${FILE%.smt2}"
            lfsc "${FILENAME}"
            verit "${FILENAME}"
            ;;
    esac

done

cat <<EOF
(alias
 (name runtest)
 (deps
  (alias_rec all)))

(rocq.theory
 (name SMTCoq.tests)
 (generate_project_file)
 (theories Stdlib SMTCoq)
 (plugins rocq-smtcoq.smtcoq)
 (modules${MODULES})
 (flags
  (:standard -I ../_build/install/default/lib)))
EOF
