#!/usr/bin/env bash

set -e

shift 1
DEPS=$@

MODULES=""


function cvc4() {
    FILENAME=$1

    [[ "${FILENAME}" == hole4 ]] && return
    [[ "${FILENAME}" =~ lia[0-9]* ]] && return
    [[ "${FILENAME}" == sat5 ]] && return
    [[ "${FILENAME}" == sat7 ]] && return
    [[ "${FILENAME}" == sat9 ]] && return
    [[ "${FILENAME}" == sat10 ]] && return
    [[ "${FILENAME}" == sat11 ]] && return
    [[ "${FILENAME}" == sat12 ]] && return
    [[ "${FILENAME}" == sat13 ]] && return
    [[ "${FILENAME}" == sat14 ]] && return
    [[ "${FILENAME}" == uf1 ]] && return
    [[ "${FILENAME}" == uf3 ]] && return
    [[ "${FILENAME}" == uf4 ]] && return
    [[ "${FILENAME}" == uf5 ]] && return

    cat <<EOF
(rule
 (target ${FILENAME}.lfsc)
 (deps ${FILENAME}.smt2)
 (action
  (with-stdout-to
   %{target}
   (run
    cvc4
    --proof
    --dump-proof
    --fewer-preprocessing-holes
    --no-bv-eq
    --no-bv-ineq
    --no-bv-algebraic
    --allow-empty-dependencies
    %{deps}))))

EOF

    cat <<EOF
(rule
 (target lfsc_${FILENAME}.v)
 (deps ${FILENAME}.smt2 ${FILENAME}.lfsc)
 (action
  (write-file
   %{target}
   "From Stdlib Require Import Bool List.\nFrom SMTCoq Require Import BVList FArray Tactics.\nSection File.\n  Lfsc_Checker \"unit-tests/${FILENAME}.smt2\" \"unit-tests/${FILENAME}.lfsc\".\nEnd File.\n")))

EOF

    MODULES+=$'\n'"  lfsc_${FILENAME}"
}



cat <<EOF
; This file has been generated by dune. Do not edit.
; Once this file is modified, track it with git.

EOF

for FILE in ${DEPS}
do
    FILENAME="${FILE%.smt2}"

    cvc4 "${FILENAME}"
done

cat <<EOF
(rocq.theory
 (name SMTCoq.tests)
 (theories Stdlib SMTCoq)
 (plugins rocq-smtcoq.smtcoq)
 (modules ${MODULES}))
EOF
