#!/usr/bin/env bash

set -e

shift 1
DEPS=$*

MODULES=""


function lfsc() {
    FILENAME=$1

    [[ "${FILENAME}" == hole4 ]] && return
    [[ "${FILENAME}" =~ lia[0-9]* ]] && return
    [[ "${FILENAME}" == sat5 ]] && return
    [[ "${FILENAME}" == sat7 ]] && return
    [[ "${FILENAME}" == sat9 ]] && return
    [[ "${FILENAME}" == sat10 ]] && return
    [[ "${FILENAME}" == sat11 ]] && return
    [[ "${FILENAME}" == sat12 ]] && return
    [[ "${FILENAME}" == sat13 ]] && return
    [[ "${FILENAME}" == sat14 ]] && return
    [[ "${FILENAME}" == uf1 ]] && return
    [[ "${FILENAME}" == uf3 ]] && return
    [[ "${FILENAME}" == uf4 ]] && return
    [[ "${FILENAME}" == uf5 ]] && return

    cat <<EOF
(rule
 (target ${FILENAME}.lfsc)
 (deps ${FILENAME}.smt2)
 (action
  (with-stdout-to
   %{target}
   (run
    cvc4
    --proof
    --dump-proof
    --fewer-preprocessing-holes
    --no-bv-eq
    --no-bv-ineq
    --no-bv-algebraic
    --allow-empty-dependencies
    %{deps}))))

EOF

    cat <<EOF
(rule
 (target vernac_lfsc_${FILENAME}.v)
 (deps ${FILENAME}.smt2 ${FILENAME}.lfsc)
 (action
  (write-file
   %{target}
   "From SMTCoq Require Import SMTCoq.\nSection File.\n  Lfsc_Checker \"unit-tests/${FILENAME}.smt2\" \"unit-tests/${FILENAME}.lfsc\".\nEnd File.\n")))

EOF

    MODULES+=$'\n'"  vernac_lfsc_${FILENAME}"
}


function verit() {
    FILENAME=$1

    [[ "${FILENAME}" == bv1 ]] && return
    [[ "${FILENAME}" == bv2 ]] && return
    [[ "${FILENAME}" == ex1 ]] && return
    [[ "${FILENAME}" == sat10 ]] && return

    cat <<EOF
(rule
 (target ${FILENAME}.vtlog)
 (deps ${FILENAME}.smt2)
 (action
  (ignore-stdout
   (run
    veriT
    --proof-prune
    --proof-merge
    --proof-with-sharing
    --cnf-definitional
    --disable-ackermann
    --input=smtlib2
    --proof=%{target}
    %{deps}))))

EOF

    cat <<EOF
(rule
 (target vernac_verit_${FILENAME}.v)
 (deps ${FILENAME}.smt2 ${FILENAME}.vtlog)
 (action
  (write-file
   %{target}
   "From SMTCoq Require Import SMTCoq.\nSection File.\n  Verit_Checker \"unit-tests/${FILENAME}.smt2\" \"unit-tests/${FILENAME}.vtlog\".\nEnd File.\n")))

EOF

    MODULES+=$'\n'"  vernac_verit_${FILENAME}"
}


function zchaff() {
    FILENAME=$1

    cat <<EOF
(rule
 (target ${FILENAME}.zlog)
 (deps run_zchaff.sh ${FILENAME}.cnf)
 (action
  (ignore-stdout
   (run ./run_zchaff.sh %{deps} %{target}))))

EOF

    cat <<EOF
(rule
 (target vernac_zchaff_${FILENAME}.v)
 (deps ${FILENAME}.cnf ${FILENAME}.zlog)
 (action
  (write-file
   %{target}
   "From SMTCoq Require Import SMTCoq.\nSection File.\n  Zchaff_Checker \"unit-tests/${FILENAME}.cnf\" \"unit-tests/${FILENAME}.zlog\".\nEnd File.\n")))

EOF

    MODULES+=$'\n'"  vernac_zchaff_${FILENAME}"
}


cat <<EOF
; This file has been generated by dune. Do not edit.
; Once this file is modified, track it with git.

EOF

for FILE in ${DEPS}
do

    case "${FILE}" in
        *.cnf)
            FILENAME="${FILE%.cnf}"
            zchaff "${FILENAME}"
            ;;
        *.smt2)
            FILENAME="${FILE%.smt2}"
            lfsc "${FILENAME}"
            verit "${FILENAME}"
            ;;
    esac

done

cat <<EOF
(rocq.theory
 (name SMTCoq.tests)
 (theories Stdlib SMTCoq)
 (plugins rocq-smtcoq.smtcoq)
 (modules${MODULES}))
EOF
