on:
  push:
    branches:
      - coq-8.13
      - coq-8.14
      - coq-8.15
      - coq-8.16
  pull_request:
    branches:
      - coq-8.13
      - coq-8.14
      - coq-8.15
      - coq-8.16

jobs:
  test-and-install:
    runs-on: ubuntu-latest
    env:
      push: ${{ github.ref_name }}
      pull_request: ${{ github.base_ref }}
    strategy:
      matrix:
        image:
          - smtcoq/smtcoq:latest-${{ env[github.event_name] }}
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - run: echo "yeepee"
