on:
  push:
    branches:
      - coq-8.13
      - coq-8.14
      - coq-8.15
      - coq-8.16
  pull_request:
    branches:
      - coq-8.13
      - coq-8.14
      - coq-8.15
      - coq-8.16

jobs:
  test-and-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - smtcoq/smtcoq:latest-${{ github.base_ref }}
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-smtcoq.opam'
          custom_image: ${{ matrix.image }}
      - run: echo "smtcoq/smtcoq:latest-${{ fromJSON('[\"push\"=>github.ref_name, \"pull_request\"=>github.base_ref]')[github.event_name] }}"
