name: Build SMTCoq against supported released versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35

      - uses: ryanccn/attic-action@v0
        with:
          cache: smtcoq
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build the current version in nixpkgs
        run: nix build .#smtcoq --print-build-logs

      - name: Build the whole matrix of supported released versions
        run: nix flake check --print-build-logs
