name: Build SMTCoq against specific versions

on:
  pull_request:
    branches: [ rocq-master ]
  schedule:
    - cron: '0 4 * * 5'
  workflow_dispatch:
    inputs:
      rocq:
        description: Rocq version or commit
      stdlib:
        description: Stdlib version or commit
      rocq-elpi:
        description: Rocq-Elpi version or commit
      trakt:
        description: Trakt version or commit
      smtcoq:
        description: SMTCoq version or commit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35

      - name: Build against specific versions
        run: |
          nix build --impure --expr '
            let
              flake = builtins.getFlake (toString ./.);
              pkgs = import flake.inputs.nixpkgs {
                system = "x86_64-linux";
                overlays = [ flake.overlays.default ];
              };
            in
            flake.lib.mkSMTCoq pkgs {
              rocq = "${{ inputs.rocq || 'master' }}";
              stdlib = "${{ inputs.stdlib || 'master' }}";
              rocq-elpi = "${{ inputs.rocq-elpi || 'master' }}";
              trakt = "${{ inputs.trakt || 'master' }}";
              smtcoq = "${{ inputs.smtcoq || 'rocq-master' }}";
            }' --print-build-logs
